version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wiz_guide_fn.wsgi:application --access-logfile - --error-logfile -
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Теперь Django ждёт, пока БД будет готова
    env_file:
      - .env  

  db:
  image: postgres:15
  restart: always
  env_file:
    - .env  # Здесь указаны переменные, как например POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata  # Указываем директорию для хранения данных PostgreSQL
  volumes:
    - postgres_data:/var/lib/postgresql/data  # Для сохранения данных между перезапусками
  ports:
    - "5432:5432"
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    interval: 10s
    retries: 5